sign:
    line1: bla
    line2: bli
    line3: blubb
    line4: diblubb
handy:
    kosten: 15
    proMinute: 0.19
sms:
    kosten: 1.0
towers:
    blocks:
        down: IRON_BLOCK
        middown: IRON_BLOCK
        midtop: IRON_BLOCK
        top: BEACON
    maxdistance: 100.0