name: Conversations
version: 0.1
main: org.exodevil.Conversations.Conversations
author: Exodevil
website: http://edgecraft.de/

commands:
    conversation:
        description: bla
        usage: /<command>