sign:
    text1: bla
    text2: bli
    text3: blubb
    text4: diblubb
handy:
    kosten: 15
    proMinute: 0.19
sms:
    kosten: 1.0
towers:
    blocks:
        down: IRON_BLOCK
        middown: IRON_BLOCK
        midtop: IRON_BLOCK
        top: BEACON
    maxdistance: 100.0